services:
  node01:
    build: .
    tty: true
    volumes:
      - .:/go/src/app
    command: go run cmd/server/main.go --name node01 --host 172.26.250.11 --port 8000
    networks:
      cluster:
        ipv4_address: 172.26.250.11

  node02:
    build: .
    tty: true
    volumes:
      - .:/go/src/app
    command: go run cmd/server/main.go --name node02 --host 172.26.250.12 --port 8000 --server 172.26.250.11:8000
    depends_on:
      - "node01"
    networks:
      cluster:
        ipv4_address: 172.26.250.12

  node03:
    build: .
    tty: true
    volumes:
      - .:/go/src/app
    command: go run cmd/server/main.go --name node03 --host 172.26.250.13 --port 8000 --server 172.26.250.11:8000
    depends_on:
      - "node01"
    networks:
      cluster:
        ipv4_address: 172.26.250.13

  node04:
    build: .
    tty: true
    volumes:
      - .:/go/src/app
    command: go run cmd/server/main.go --name node04 --host 172.26.250.14 --port 8000 --server 172.26.250.11:8000
    depends_on:
      - "node01"
    networks:
      cluster:
        ipv4_address: 172.26.250.14

  node05:
    build: .
    tty: true
    volumes:
      - .:/go/src/app
    command: go run cmd/server/main.go --name node05 --host 172.26.250.15 --port 8000 --server 172.26.250.11:8000
    depends_on:
      - "node01"
    networks:
      cluster:
        ipv4_address: 172.26.250.15

  client:
    build: .
    tty: true
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app/cmd/client
    networks:
      cluster:
        ipv4_address: 172.26.250.2

networks:
  cluster:
    ipam:
      driver: default
      config:
        - subnet: 172.26.250.0/24
